keys:
  - &users:
    - &taxborn age1r7x3vjkzg3yk77ldmp3p5w9wxfm07skxgcu3fkrhm30v3carm9zsqlfzap
  - &hosts:
    - &uranium age10p333a5rddeje7ljg5ty8g359648pjtw76clug457uazh34s2gnqtnst0x
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *uranium
          - *taxborn
