keys:
  - &users:
    - &taxborn age1r7x3vjkzg3yk77ldmp3p5w9wxfm07skxgcu3fkrhm30v3carm9zsqlfzap
  - &hosts:
    - &uranium age10p333a5rddeje7ljg5ty8g359648pjtw76clug457uazh34s2gnqtnst0x
    - &tungsten age1xs98v3v2ggtwfl02xkh95twnf55qm2qzzrlyc4z5407u77fnzassg22qwt
    - &carbon age1usqgyr3uq2a5gl67k0ut8mzwydwjtq5tvvztg47u9lyxctws4v4s3lv6eh
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *uranium
          - *tungsten
          - *carbon
          - *taxborn
